//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AppointmentTable
{
    public int AppointmentId { get; set; }
    public string Reason { get; set; }
    public System.DateTime AppDate { get; set; }
    public System.TimeSpan AppTime { get; set; }
    public Nullable<int> PatientID { get; set; }
    public Nullable<int> DoctorID { get; set; }
    public Nullable<int> HospitalID { get; set; }
    public Nullable<int> DepartmentID { get; set; }
}

public partial class DepartmentTable
{
    public int DepartmentId { get; set; }
    public string Specialization { get; set; }
    public int HospitalID { get; set; }
    public string Location { get; set; }
    public string Contact { get; set; }
}

public partial class DoctorTable
{
    public int DoctorId { get; set; }
    public int DepartmentID { get; set; }
    public string DoctorName { get; set; }
    public string ContactDoctor { get; set; }
    public string DoctorUserName { get; set; }
    public string PhoneNumber { get; set; }
}

public partial class EmailTable
{
    public int EmailsId { get; set; }
    public string TO { get; set; }
    public string FROM { get; set; }
    public string EmailText { get; set; }
}

public partial class HospitalTable
{
    public int HospitalID { get; set; }
    public string HosptialName { get; set; }
    public string HosptialAddress { get; set; }
    public string State { get; set; }
    public string ContactInfo { get; set; }
}

public partial class PatientTable
{
    public int PatientID { get; set; }
    public string PatientAddress { get; set; }
    public string PatientCity { get; set; }
    public string PatientState { get; set; }
}
