//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class TableForAppointment
{
    public int Id { get; set; }
    public Nullable<int> patientID { get; set; }
    public Nullable<int> doctorID { get; set; }
    public string time { get; set; }
    public Nullable<int> hospitalID { get; set; }
}

public partial class TableForDepartment
{
    public int Id { get; set; }
    public Nullable<int> DepartmentNumber { get; set; }
}

public partial class TableForDoctor
{
    public int Id { get; set; }
    public string docName { get; set; }
    public Nullable<int> departmentID { get; set; }
}

public partial class TableForEmail
{
    public int Id { get; set; }
    public string To { get; set; }
    public string From { get; set; }
    public string text { get; set; }
}

public partial class TableForHospital
{
    public int Id { get; set; }
    public Nullable<int> doctorID { get; set; }
    public string hospitalName { get; set; }
}

public partial class TableForPatient
{
    public int Id { get; set; }
    public string PatientName { get; set; }
    public Nullable<int> appointmentID { get; set; }
}
