//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class SystemEntities2 : DbContext
{
    public SystemEntities2()
        : base("name=SystemEntities2")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<TableForAppointment> TableForAppointments { get; set; }
    public virtual DbSet<TableForDepartment> TableForDepartments { get; set; }
    public virtual DbSet<TableForDoctor> TableForDoctors { get; set; }
    public virtual DbSet<TableForEmail> TableForEmails { get; set; }
    public virtual DbSet<TableForHospital> TableForHospitals { get; set; }
    public virtual DbSet<TableForPatient> TableForPatients { get; set; }
}
